version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install phase"
  
  build:
    commands:
      - echo "Building and packaging the lambda functions"

      # Make output dir
      - mkdir -p artifacts

      # zip each lambda function
      - echo "Zipping index-photos-1"
      - cd lambdas/index-photos-1
      - zip -r ../../artifacts/index-photos-1.zip .
      - cd ../../

      - echo "Zipping search-photos"
      - cd lambdas/search-photos
      - zip -r ../../artifacts/search-photos.zip .
      - cd ../../

      # Deploy the lambda functions
      - aws lambda update-function-code --function-name index-photos-1 --zip-file fileb://artifacts/index-photos-1.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://artifacts/search-photos.zip

artifacts:
  files:
    - artifacts/*